### ISSUE TITLE
Support crypto/x509.SystemCertPool

### ISSUE THREAD

**Issue by whilp** [github/smimesign#23]
Currently, smimesign relies on system trust stores (via #7) for Darwin and Windows. This leaves other systems (namely linux) unable to build:

```
$ go get github.com/github/smimesign
# github.com/github/smimesign/vendor/github.com/mastahyeti/certstore
../src/github.com/github/smimesign/vendor/github.com/mastahyeti/certstore/certstore.go:17:9: undefined: openStore
$ echo $?
2
```

One solution (I think) would be to add support for Go's [CertPool](https://golang.org/pkg/crypto/x509/#CertPool). This could be a suitable backend in certstore; at a glance, I believe the interface is compatible:

https://github.com/github/smimesign/blob/df6b0fff6e3d6c986097700afc82e13821120f6c/vendor/github.com/mastahyeti/certstore/certstore.go#L15-L49

<details>
<summary>go env</summary>

```
$ go env
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/me/.cache/go-build"
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/me"
GORACE=""
GOROOT="/usr/local/go"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build685245200=/tmp/go-build -gno-record-gcc-switches"
```

</summary>

**Comment by mastahyeti** [comment]
The `*x509.CertStore` type is a wrapper around a set of certificates, allowing them to be used for chain building when verifying another certificate. This doesn't give any access to the private keys associated with these certificates or allow you to sign things with their keys. The smimesign tool relies on the [github.com/mastahyeti/certstore](https://github.com/mastahyeti/certstore) package to provide the functionality of talking to the system certificate store for using user identities for signing. This package serves a very different purpose from `*x509.CertStore` and the two aren't interchangeable. 

It would be great if smimesign could work on Linux, but that would require a Linux-specific implementation to be added to [github.com/mastahyeti/certstore](https://github.com/mastahyeti/certstore). As far as I know, there isn't one client certificate store that is commonly used across Linux distributions like there is for macOS and Windows. This makes it difficult to implement a general purpose Linux implementation. I think the best option for Linux users currently is to stick with `gpgsm`, which is distributed with GnuPG and implements its own certificate store instead of trying to use the system's.
