### ISSUE TITLE
fetching public keys from keyserver

### ISSUE THREAD

**Issue by henning-schild** [github/smimesign#58]
On Linux `gpgsm` will use its `dirmngr` to fetch certificates from LDAP. In most cooperate setups that is going to be the Active Directory LDAP. That is also where Email clients get it from. Not sure whether that is a direct call to LDAP or a call to the OS's trust/cert store.

What i do see on Windows is that i can verify my own signatures but verification of other signatures fails. And i assume the reason is that the certificates are not yet known and need to be fetched from the keyserver. I could not really verify that yet.

Maybe someone can explain how i browse the trust-store on Windows, and how i would manually import a cert into it.

But if the asumtion is correct smimesign needs to import the certs when encountered. I would hope that there are libraries that can just be called on MacOS and Windows. Something like OS.smime.find_and_import_according_to_global_config(email)

**Comment by mastahyeti** [comment]
My understanding is that the Windows CrytpoAPI should be searching remote servers when asked to build a certificate chain. That is the API used by the [certstore](https://github.com/mastahyeti/certstore) library that smimesign is built on top of. I am not a Windows user though and I have only performed minimal testing on how these APIs work in practice. Similarly, certstore uses the Security framework to build chains on macOS. This framework claims to try fetching missing intermediates, though it isn't clear whether this can work with LDAP or just making HTTP requests based on the AIA extension.

I'm happy to keep discussing this, but I am closing this issue for now since it doesn't represent a bug.

**Comment by henning-schild** [comment]
Ok. I would not be surprised if the failed verifications i am seeing are a configuration issue of the managed Windows i experimented on. Let us see if this pops up for anyone else.

I did investigate a bit and could not find my co-workers in the certstore. Manually importing the certs from LDAP did not resolve the issue. However i.e. Outlook does somehow finds those certs while smimesign does not. But again that could be a wrongly configured certstore + an outlook hack.

**Comment by mastahyeti** [comment]
I'd give equal odds of it being an issue with certstore. I don't have access to a production environment where certs are distributed by LDAP, so all of my development efforts have been based on contrived setups.
