### ISSUE TITLE
Mention incompatibility with linux in readme?

### ISSUE THREAD

**Issue by yabbes** [github/smimesign#63]
Maybe it's just me, but I put some time in this because we thought we could use smimesign for our project. I tried to compile from source as per instructions given in your readme.
Only to find out just now that smimesign depends on a go library (certstore) that is not supported in linux environments (yet).

->
https://github.com/github/certstore/blob/master/certstore_linux.go

```
package certstore

import "errors"

// This will hopefully give a compiler error that will hint at the fact that
// this package isn't designed to work on Linux.
func init() {
	CERTSTORE_DOESNT_WORK_ON_LINIX
}
```

Just thought if you could mention this in your readme maybe it would save someone else's time so they don't have to go through the whole process only to find out it's not supported.

**Comment by lgarron** [comment]
The first sentence in `README.md` is:

> Smimesign is an S/MIME signing utility for macOS and Windows that is compatible with Git. 

How helpful would it be to mention a Linux incompatibility explicitly?

**Comment by bufferoverflow** [comment]
@lgarron I agree and think this can be closed.

**Comment by lgarron** [comment]
I'm closing this for now. We can always revisit if more people stumble into this.

**Comment by squillace** [comment]
Uh, @lgarron I just hit this because I'm on Linux and the GitHub docs POINT as SMIME and whilst it says Mac and Windows, _one would assume that using Go installation would likely work_ -- so I just ran into this as well. 

Functionally speaking, I now will begin to militate to my colleagues to use GPG because it's portable. I'm not irritated in any way! Trust me. :-) but I wanted to use smime, and I cannot now without going and working upstream to enable it. So gpg it is.

Just food for braining, not a blocker to the world. :-)

**Comment by squillace** [comment]
![image](https://user-images.githubusercontent.com/1422718/110020029-15d55180-7cf7-11eb-860c-137038d52447.png)

**Comment by squillace** [comment]
I rather think it would be better for GH docs to state outright that if you want to use Linux you have only one solution.
